VERSION=2.2.3

all: 
	pdflatex -jobname="rhb-${VERSION}.pdf" rhb
	pdflatex -jobname="rhb-${VERSION}.pdf" rhb
	if not exist pdf mkdir pdf
	move *.pdf pdf

clean:
	powershell -Command "Remove-Item -Path *.log, *.aux, *.out, *.toc -ErrorAction Ignore"
	powershell -Command "Remove-Item -Path pdf\*.pdf -ErrorAction Ignore"
	powershell -Command "Remove-Item -Path pdf\ -ErrorAction Ignore"
	